ads/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;
using System.Web.Mvc;

namespace ads.Models
{

    public partial class Message
    {
        [Display(Name = "Текст сообщение")]
        [StringLength(255)]
        [UIHint("MultilineText")]
        public string text { get; set; }

        [Display(Name = "Дата")]
        public DateTime? datetime { get; set; }
        
        public bool? isRead { get; set; }

        [StringLength(128)]
        public string idSender { get; set; }

        [HiddenInput(DisplayValue = false)]
        public int id { get; set; }

        public virtual ApplicationUser UserSender { get; set; }

        public int idChat { get; set; }

        public virtual Chat Chat { get; set; }

    }
}

ads/Models/MessageViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;
using System.Web.Mvc;

namespace ads.Models
{
    public class DialogViewModel
    {
        public Chat Chatt;
        public int CountMess;
        public List<ChatUser> Chaters;
    }
    public class MessageToAdminViewModel
    {
        [Display(Name = "Текст сообщение")]
        [StringLength(255)]
        [UIHint("MultilineText")]
        public string text { get; set; }

        [Display(Name = "Тема")]
        [StringLength(128)]
        public string title { get; set; }

    }
}

ads/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ads.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Configuration;

namespace ads.Controllers
{
    public class MessagesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //// GET: Messages
        public async Task<ActionResult> Index()
        {
            var messages = db.Messages.Include(m => m.UserSender);
            return View(await messages.ToListAsync());
        }

        //// GET: Dialogs
        //public async Task<ActionResult> Dialogs()
        //{
        //    string idUser = User.Identity.GetUserId();
        //    ApplicationUser user = await UserManager.FindByIdAsync(idUser);
        //    //Ad ad = 
        //    var mes = await db.Messages.Where(m => m.idRecipient == idUser
        //    || m.idSender == idUser).GroupBy(m => m..ToListAsync();
        //    DialogViewModel dialogs = new DialogViewModel() { User = user, Messages = mes };
        //    var messages = db.Messages.Include(m => m.Ad).Include(m => m.UserRecipient).Include(m => m.UserSender);
        //    await messages.ToListAsync();
        //    return View(dialogs);
        //}

        // GET: Messages/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = await db.Messages.FindAsync(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // GET: Messages/Create
        public ActionResult Create()
        {
            //ViewBag.idAd = new SelectList(db.Ads, "id", "title");
            //  ViewBag.idRecipient = new SelectList(db.ApplicationUsers, "Id", "Email");
            // ViewBag.idSender = new SelectList(db.ApplicationUsers, "Id", "Email");
            return View();
        }

        // POST: Messages/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateWithAd([Bind(Include = "text")] Message message,
            int? idAd)
        {
                if (User.Identity.IsAuthenticated)
                {

                if (ModelState.IsValid)
                {
                    var idSender = User.Identity.GetUserId();
                    message.idSender = idSender;
                    message.isRead = false;
                    message.datetime = DateTime.Now;

                    Chat Chat;
                
                        bool isExistChat = await db.ChatUser.Where
                            (chat => chat.Chat.idAd == idAd && chat.idUser == idSender).CountAsync() > 0;

                        if (isExistChat)
                        {
                            var ChatUser = await db.ChatUser.Where
                            (chat => chat.Chat.idAd == idAd && chat.User.Id == idSender).FirstAsync();
                            Chat = ChatUser.Chat;
                        }
                        else
                        {
                            var Ad = await db.Ads.FindAsync(idAd);
                            Chat = new Chat();
                            Chat.idAd = idAd;
                            db.Chats.Add(Chat);
                            await db.SaveChangesAsync();

                            ChatUser chatUser1 = new ChatUser();
                            ChatUser chatUser2 = new ChatUser();

                            chatUser1.idChat = Chat.id;
                            chatUser1.idUser = Ad.idUser;

                            chatUser2.idChat = Chat.id;
                            chatUser2.idUser = idSender;

                            db.ChatUser.Add(chatUser1);
                            db.ChatUser.Add(chatUser2);

                            await db.SaveChangesAsync();
                        }
                    message.idChat = Chat.id;
                    db.Messages.Add(message);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index","ChatUsers",new { });
                }
                return View("",new Ad{ id=(int)idAd});
            }
            return RedirectToAction("Login", "Account", null);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "text")] Message message,
           int? idChat)
        {
            if (ModelState.IsValid)
            {
                if (User.Identity.IsAuthenticated)
                {
                    var idSender = User.Identity.GetUserId();
                    message.idSender = idSender;
                    message.isRead = false;
                    message.datetime = DateTime.Now;

                    Chat Chat;
                    
                    Chat = new Chat { id = (int)idChat };

                    message.idChat = Chat.id;
                    db.Messages.Add(message);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index", "ChatUsers", new { });

                }
                return RedirectToAction("Login", "Account", null);
            }
            return View(message);
        }
        // GET: Messages/GetContac
        [Authorize]
        public ActionResult GetContact()
        {
            //ViewBag.idAd = new SelectList(db.Ads, "id", "title");
            //  ViewBag.idRecipient = new SelectList(db.ApplicationUsers, "Id", "Email");
            // ViewBag.idSender = new SelectList(db.ApplicationUsers, "Id", "Email");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> CreateToAdmin([Bind(Include = "text, title")] MessageToAdminViewModel message)
        {
            if (ModelState.IsValid)
            { 
                Message newMessage = new Message();
            var idSender = User.Identity.GetUserId();
            newMessage.idSender = idSender;
            newMessage.isRead = false;
            newMessage.datetime = DateTime.Now;

            Chat newChat = new Chat();
            newChat.title = message.title;

            db.Chats.Add(newChat);
            await db.SaveChangesAsync();

            ChatUser chatUser1 = new ChatUser();
            ChatUser chatUser2 = new ChatUser();

            chatUser1.idChat = newChat.id;
            chatUser1.idUser = idSender;

            string admin = ConfigurationManager.AppSettings.Get("AdminToConnection");
            chatUser2.idChat = newChat.id;
            chatUser2.idUser = admin;

            db.ChatUser.Add(chatUser1);
            db.ChatUser.Add(chatUser2);

            await db.SaveChangesAsync();


            newMessage.idChat = newChat.id;
            db.Messages.Add(newMessage);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
            return View(message);
        }

        //public async Task<ActionResult> Create([Bind(Include = "text")] Message message,
        //  int? idAd)
        //{
        //    if (User.Identity.IsAuthenticated)
        //    {
        //        var idSender = User.Identity.GetUserId();
        //        message.idSender = idSender;
        //        message.isRead = false;
        //        message.datetime = DateTime.Now;

        //        Chat Chat;

        //        bool isExistChat = await db.ChatUser.Where
        //            (chat => chat.Chat.idAd == idAd && chat.User.Id == idSender).CountAsync() > 0;
        //        if (isExistChat)
        //        {
        //            var ChatUser = await db.ChatUser.Where
        //            (chat => chat.Chat.idAd == idAd && chat.User.Id == idSender).FirstAsync();
        //            Chat = ChatUser.Chat;
        //        }
        //        else
        //        {
        //            var Ad = await db.Ads.FindAsync(idAd);
        //            Chat = new Chat();
        //            Chat.idAd = idAd;
        //            db.Chats.Add(Chat);
        //            await db.SaveChangesAsync();

        //            ChatUser chatUser1 = new ChatUser();
        //            ChatUser chatUser2 = new ChatUser();

        //            chatUser1.idChat = Chat.id;
        //            chatUser1.idUser = Ad.idUser;

        //            chatUser2.idChat = Chat.id;
        //            chatUser2.idUser = idSender;

        //            db.ChatUser.Add(chatUser1);
        //            db.ChatUser.Add(chatUser2);

        //            await db.SaveChangesAsync();
        //        }


        //        message.idChat = Chat.id;
        //        db.Messages.Add(message);
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("Index");

        //    }

        //    return RedirectToAction("~/Views/Account/Login.cshtml");
        //    //if (ModelState.IsValid)
        //    //{

        //    //}

        //    //ViewBag.idAd = new SelectList(db.Ads, "id", "title", message.idAd);

ads/Views/Messages/CreateByChatPartial.cshtml
@model ads.Models.Message

<div class="comment-form-wrap pt-5">
    <h3 class="mb-5">Написать личное сообщение</h3>
    @using (Html.BeginForm("Create", "Messages", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("idChat", Model.Chat.id as int?)
        <div class="sidebar-box col text-center">
            <div class="form-group">
                <div class="col-md-10 ">
                    @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control",

                @cols = "30", @rows = "5"
               } })
                    @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
                <div class="sidebar-box col text-center">
                    <div class="form-group">
                        <input type="submit" value="Отправить" class="btn btn-primary py-3 px-5">
                    </div>
                </div>
    }
    </div>

ads/Views/Messages/CreatePartial.cshtml
@model ads.Models.Message

<div class="comment-form-wrap pt-5">
    <h3 class="mb-5">Написать личное сообщение</h3>
    @using (Html.BeginForm("CreateWithAd", "Messages", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("idAd", Model.Chat.idAd as int?)
        @*@if (Model.Chat.id != 0)
        {
        @Html.Hidden("idChat", Model.Chat.id as int?)
        }*@
        <div class="sidebar-box col text-center">
            <div class="form-group">
                <div class="col-md-10 ">
                    @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control",

                @cols = "30", @rows = "5"
               } })
                    @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
                <div class="sidebar-box col text-center">
                    <div class="form-group">
                        <input type="submit" value="Отправить" class="btn btn-primary py-3 px-5">
                    </div>
                </div>
    }
    </div>

ads/Views/Messages/Delete.cshtml
@model ads.Models.Message

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Message</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ad.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ad.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserRecipient.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserRecipient.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserSender.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserSender.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isRead)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isRead)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ads/Views/Messages/Details.cshtml
@model ads.Models.Message

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Message</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ad.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ad.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserRecipient.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserRecipient.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserSender.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserSender.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isRead)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isRead)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ads/Views/Messages/Dialogs.cshtml
@model ads.Models.DialogViewModel
@{
    ViewBag.Title = "Dialogs";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<h2>Dialogs</h2>


    @Html.DisplayFor(model=>model.User.Id)
<br />
<p>
    @foreach (var item in Model.Messages)
    {
        <tr>
            <td>
                -----
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.text)
            </td>
        </tr>

        <tr>
            <td>
                -----
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ad.title)
            </td>
        </tr>
    }
</p>

ads/Views/Messages/Edit.cshtml
@model ads.Models.Message

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Message</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.datetime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datetime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.datetime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isRead, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.isRead, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.isRead, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idAd, "idAd", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idAd", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idAd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idSender, "idSender", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idSender", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idSender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idRecipient, "idRecipient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idRecipient", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idRecipient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ads/Views/Messages/GetContact.cshtml
@model ads.Models.MessageToAdminViewModel
@{
    ViewBag.Title = "GetContact2";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<h2>GetContact2</h2>

<div class="col-md-6 order-md-last d-flex">
    @using (Html.BeginForm("CreateToAdmin", "Messages", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>
            <div class="form-group">
                <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
            </div>
    }
</div>

ads/Views/Messages/Index.cshtml
@model IEnumerable<ads.Models.Message>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserSender.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.datetime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isRead)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserSender.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.datetime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isRead)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

ads/Views/Messages/Send.cshtml
@model ads.Models.Message

@if (ViewBag.formMessage == true)
{

    <div class="col-md-6 order-md-last d-flex">
        @using (Html.BeginForm("Create", "Messages", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.Hidden("idAd", @ViewBag.idAd as int?)
          

            <div class="form-group">
                <div class="col-md-10">
                    @Html.EditorFor(model=> model.text, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
            </div>
        }
    </div>
    }