ads/Models/ChatUser.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;
using System.Web.Mvc;

namespace ads.Models
{
    public class ChatUser
    {
        [Key]
        [Column(Order =0)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int idChat { get; set; }

        [Key]
        [Column(Order = 1)]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [StringLength(128)]
        public string idUser { get; set; }

        public virtual ApplicationUser User { get; set; }

        public virtual Chat Chat { get; set; }
    }
}

ads/Controllers/ChatUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ads.Models;
using Microsoft.AspNet.Identity;
using PagedList;

namespace ads.Controllers
{
    public class ChatUsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ChatUsers
        [Authorize]
        public async Task<ActionResult> Index(int? page)
        {
            int pageNumber = (page ?? 1);
            var CurrentUser = User.Identity.GetUserId();
            var groupchat = await db.ChatUser.Where(chatus => chatus.idUser == CurrentUser).Select(chat =>
            new DialogViewModel
            {
                Chatt = chat.Chat,
                CountMess = chat.Chat.Messages.Where(mes => mes.isRead == false &&
                mes.idSender!=CurrentUser).Count(),
                Chaters = chat.Chat.ChatUsers.Where(c => c.idUser != CurrentUser).ToList()
            }).ToListAsync();

            //var chatUser = db.ChatUser.Where(chatus => chatus.idUser==CurrentUser)
            //    .Include(c => c.Chat).Include(c => c.User);

            return View(groupchat.ToPagedList(pageNumber, 6));
        }

        // GET: ChatUsers/Details/5
        public async Task<ActionResult> Details(int? idChat)
        {
            if (idChat == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ChatUser chatUser = await db.ChatUser.FindAsync(idChat);
            if (chatUser == null)
            {
                return HttpNotFound();
            }
            return View(chatUser);
        }

        // GET: ChatUsers/Create
        public ActionResult Create()
        {
            ViewBag.idChat = new SelectList(db.Chats, "id", "title");
            ViewBag.idUser = new SelectList(db.ApplicationUsers, "Id", "Email");
            return View();
        }

        // POST: ChatUsers/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "idChat,idUser")] ChatUser chatUser)
        {
            if (ModelState.IsValid)
            {
                db.ChatUser.Add(chatUser);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.idChat = new SelectList(db.Chats, "id", "title", chatUser.idChat);
            ViewBag.idUser = new SelectList(db.ApplicationUsers, "Id", "Email", chatUser.idUser);
            return View(chatUser);
        }

        // GET: ChatUsers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChatUser chatUser = await db.ChatUser.FindAsync(id);
            if (chatUser == null)
            {
                return HttpNotFound();
            }
            ViewBag.idChat = new SelectList(db.Chats, "id", "title", chatUser.idChat);
            ViewBag.idUser = new SelectList(db.ApplicationUsers, "Id", "Email", chatUser.idUser);
            return View(chatUser);
        }

        // POST: ChatUsers/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "idChat,idUser")] ChatUser chatUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chatUser).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.idChat = new SelectList(db.Chats, "id", "title", chatUser.idChat);
            ViewBag.idUser = new SelectList(db.ApplicationUsers, "Id", "Email", chatUser.idUser);
            return View(chatUser);
        }

        // GET: ChatUsers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChatUser chatUser = await db.ChatUser.FindAsync(id);
            if (chatUser == null)
            {
                return HttpNotFound();
            }
            return View(chatUser);
        }

        // POST: ChatUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ChatUser chatUser = await db.ChatUser.FindAsync(id);
            db.ChatUser.Remove(chatUser);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ads/Controllers/ChatsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ads.Models;
using Microsoft.AspNet.Identity;
using PagedList.Mvc;
using PagedList;

namespace ads.Controllers
{
    public class ChatsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Chats
        public async Task<ActionResult> Index()
        {
            var chats = db.Chats.Include(c => c.Ad);
            return View(await chats.ToListAsync());
        }

        // GET: Chats/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Chat chat = await db.Chats.FindAsync(id);
            var idUser = User.Identity.GetUserId();
            if (chat == null || db.ChatUser.Where(cu=>cu.idUser==
           idUser && cu.idChat==chat.id).First()==null)
            {
                return HttpNotFound();
            }
            var notread = await db.Messages.Where(m => m.idChat == chat.id
            && m.idSender != idUser && m.isRead == false).ToListAsync();
            for(int i=0;i<notread.Count;i++)
            {
                notread[i].isRead = true;
                db.Entry(notread[i]).State = EntityState.Modified;
                await db.SaveChangesAsync();
            }
            return View(chat);
        }

        // GET: Chats/Create
        public ActionResult Create()
        {
            ViewBag.idAd = new SelectList(db.Ads, "id", "title");
            return View();
        }

        // POST: Chats/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "id,title,idAd")] Chat chat)
        {
            if (ModelState.IsValid)
            {
                db.Chats.Add(chat);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.idAd = new SelectList(db.Ads, "id", "title", chat.idAd);
            return View(chat);
        }

        // GET: Chats/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chat chat = await db.Chats.FindAsync(id);
            if (chat == null)
            {
                return HttpNotFound();
            }
            ViewBag.idAd = new SelectList(db.Ads, "id", "title", chat.idAd);
            return View(chat);
        }

        // POST: Chats/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,title,idAd")] Chat chat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chat).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.idAd = new SelectList(db.Ads, "id", "title", chat.idAd);
            return View(chat);
        }

        // GET: Chats/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chat chat = await db.Chats.FindAsync(id);
            if (chat == null)
            {
                return HttpNotFound();
            }
            return View(chat);
        }

        // POST: Chats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Chat chat = await db.Chats.FindAsync(id);
            db.Chats.Remove(chat);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ads/Views/ChatUsers/Create.cshtml
@model ads.Models.ChatUser

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ChatUser</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idChat, "idChat", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idChat", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idChat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idUser, "idUser", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idUser", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ads/Views/ChatUsers/Delete.cshtml
@model ads.Models.ChatUser

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ChatUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Chat.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chat.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ads/Views/ChatUsers/Details.cshtml
@model ads.Models.ChatUser

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ChatUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Chat.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Chat.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ads/Views/ChatUsers/Edit.cshtml
@model ads.Models.ChatUser

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ChatUser</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idChat)

        @Html.HiddenFor(model => model.idUser)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ads/Views/ChatUsers/Index.cshtml
@using PagedList.Mvc
@using Microsoft.AspNet.Identity
@model PagedList.IPagedList<ads.Models.DialogViewModel>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<section class="ftco-section bg-light ftco-bread">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center">
            <div class="col-md-10 ftco-animate">
                <p class="breadcrumbs">
                    <span class="mr-2"><a href="/Ads/Index">Домой</a></span>
                    <span>Сообщения</span>
                </p>
                <hr />
            </div>
        </div>
    </div>
</section>

@foreach (var item in Model)
{

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => item.Chatt.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => item.Chaters[0].User.UserName)
        </th>
        <th></th>
    </tr>

    <tr>
        @if (item.Chatt.title != null)
        {
            <td>
                @Html.ActionLink(item.Chatt.title, "Details", "Chats", new { id = item.Chatt.id }, null)
            </td>
        }
        else
        {
            <td>
                @Html.ActionLink(item.Chatt.Ad.title, "Details", "Chats", new { id = item.Chatt.id }, null)
            </td>
        }

        <td>
            @foreach (var chat in item.Chaters)
            {
            @Html.DisplayFor(modelItem => chat.User.UserName)

            }
        </td>
        <td>Непрочитаных:
            @Html.DisplayFor(modelItem => item.CountMess)
         </td>
        <td>
        </td>
    </tr>

</table>
}

@*Пагинация*@
<div class="row mt-3">
    <div class="block-27">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page}))
    </div>
</div>