ads/Controllers/AdsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ads.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Web.Security;
using PagedList.Mvc;
using PagedList;

namespace ads.Controllers
{
    public class AdsController : Controller 
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        private Random rnd = new Random();
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Ads
        public async Task<ActionResult> Index(int? id, int? page)
        {
            int pageNumber = (page ?? 1);
            var ads = await db.Ads.OrderByDescending(a=>a.datetime).Where(a=>a.AdStatus.name== "Активное")
                .Include(a => a.AdStatus).Include(a => a.City)
                .Include(a => a.Subject).Include(a=>a.Image).Include(a => a.User).ToListAsync();
            var subjects = await db.Subjects.Select(s => new SubjectsViewModel
            {
                Name = s.name,
                Id = s.id,
                Count = s.Ads.Count()
            }).ToListAsync();

            ViewBag.categories = subjects;
            ViewBag.catgid = null;
            if (id!=null)
            {
                ads = ads.Where(ad => ad.idSubject == id).ToList();
                ViewBag.catgid = id;
            }
            return View(ads.ToPagedList(pageNumber,6));
        }

        // GET: Ads
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> AdminIndex(int? id, int? page)
        {
                int pageNumber = (page ?? 1);
                var ads = await db.Ads.OrderByDescending(a => a.datetime).Include(a => a.AdStatus).Include(a => a.City)
                    .Include(a => a.Subject).Include(a => a.Image).Include(a => a.User).ToListAsync();
                var subjects = await db.AdStatuses.Select(s => new StatusViewModel
                {
                    Name = s.name,
                    Id = s.id,
                    Count = s.Ads.Count()
                }).ToListAsync();

                ViewBag.categories = subjects;
                ViewBag.catgid = null;
                if (id != null)
                {
                    ads = ads.Where(ad => ad.idStatusAd == id).ToList();
                    ViewBag.catgid = id;
                }
                return View(ads.ToPagedList(pageNumber, 6));
        }

        //GET: Ads/UserAds/fduf94
        public async Task<ActionResult> UserAds(string id, int? page)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            int pageNumber = (page ?? 1);
            ViewBag.id = user.Id;
            var ads = await db.Ads.Where(ad => ad.idUser == id).Include(a => a.AdStatus)
                .Include(a => a.City).Include(a => a.Subject).Include(a=>a.Image).Include(a => a.User)
                .ToListAsync();
            return View(ads.ToPagedList(pageNumber,9));
        }

        // GET: Ads/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = await db.Ads.FindAsync(id);
            if (ad == null)
            {
                return HttpNotFound();
            }
            ViewBag.buttonEdit = false;
            ViewBag.buttonDelete = false;
            ViewBag.formMessage = true;
            ViewBag.idAd = ad.id;
            var reviews = await db.Reviews.Where(r => r.idRecipient == ad.idUser).ToListAsync();
            ViewBag.Reviews = reviews.Take(10).ToList();
            if (User.Identity.IsAuthenticated)
            {
                bool isAdmin = UserManager.IsInRole(User.Identity.GetUserId(), "Admin");
                bool isOwner = (User.Identity.GetUserId() == ad.idUser);
                bool isAdActivate = ad.AdStatus.name == "Активное";
                if (isOwner)
                {
                    ViewBag.buttonEdit = true;
                    ViewBag.buttonDelete = true;
                    ViewBag.formMessage = false;


                    if (isAdActivate)
                    {
                        ViewBag.buttonEdit = false;
                    }
                }

                if ( isAdmin)
                {
                    ViewBag.buttonEdit = true;
                    ViewBag.buttonDelete = true;
                }
            }
            return View(ad);
        }

        // GET: Ads/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.idSubject = new SelectList(db.Subjects, "id", "name");
            return View();
        }

        // POST: Ads/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<ActionResult> Create([Bind(Include = "title,text,idSubject,prise")] Ad ad, 
            HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                ad.idUser = User.Identity.GetUserId();
                Image image = new Image();
                ad.AdStatus = await db.AdStatuses.Where(status => status.name == "Неактивное")?.FirstAsync();
                ad.City = await db.Cities.Where(city => city.name == "Неизвестно")?.FirstAsync();
                ad.datetime = DateTime.Now;
                db.Ads.Add(ad);

                await UploadImage(upload, ad);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.idStatusAd = new SelectList(db.AdStatuses, "id", "name", ad.idStatusAd);
            ViewBag.idCity = new SelectList(db.Cities, "id", "name", ad.idCity);
            ViewBag.idSubject = new SelectList(db.Subjects, "id", "name", ad.idSubject);
            ViewBag.idUser = new SelectList(db.Users, "Id", "Email", ad.idUser);
            return View(ad);
        }

        // GET: Ads/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Ad ad = await db.Ads.FindAsync(id);
            bool isAdmin = UserManager.IsInRole(User.Identity.GetUserId(),"Admin");
            bool isOwner = (User.Identity.GetUserId() == ad.idUser);
            ViewBag.EditStatus = false;
            if (ad == null || (isAdmin==false && isOwner==false ))
            {
                return HttpNotFound();
            }

            ViewBag.idStatusAd = new SelectList(db.AdStatuses, "id", "name", ad.idStatusAd);
            ViewBag.idCity = new SelectList(db.Cities, "id", "name", ad.idCity);
            ViewBag.idSubject = new SelectList(db.Subjects, "id", "name", ad.idSubject);
            if(isAdmin)
            {
                ViewBag.EditStatus = true;
            }
            return View(ad);
        }

        // POST: Ads/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,title,text,idImage,idSubject,idStatusAd,idCity,datetime,prise,idUser")] Ad ad,
              string action, HttpPostedFileBase upload )
        {
                if (ModelState.IsValid)
                {
                    db.Entry(ad).State = EntityState.Modified;
                    if (upload != null) await DeleteImage(ad.idImage);
                    await UploadImage(upload, ad);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            ViewBag.idStatusAd = new SelectList(db.AdStatuses, "id", "name", ad.idStatusAd);
            ViewBag.idCity = new SelectList(db.Cities, "id", "name", ad.idCity);
            ViewBag.idSubject = new SelectList(db.Subjects, "id", "name", ad.idSubject);
            return View(ad);
        }

        private async Task<Image> DeleteImage(int? id)
        {
            if(id==null)
            {
                return null;
            }
            Image img = await db.Images.FindAsync(id);
            System.IO.File.Delete(Server.MapPath("~/Content/userfiles/" + img.id + img.name));
            var adImage = await db.Ads.Where(ad => ad.idImage == id).FirstAsync();
            adImage.idImage = null;
            db.Images.Remove(img);
            await db.SaveChangesAsync();
            return img;
        }

        private async Task<Image> UploadImage(HttpPostedFileBase upload, Ad ad)
        {
            Image img = new Image();
            if (upload != null)
            {
                string fileName = System.IO.Path.GetFileName(upload.FileName);
                img.name = fileName;
                img.idAd = ad.id;
                db.Images.Add(img);
                await db.SaveChangesAsync();

ads/Views/Shared/ADSLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Capture - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,700" rel="stylesheet">

    <link rel="stylesheet" href="~/Content/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/css/animate.css">

    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Content/css/magnific-popup.css">

    <link rel="stylesheet" href="~/Content/css/aos.css">

    <link rel="stylesheet" href="~/Content/css/ionicons.min.css">

    <link rel="stylesheet" href="~/Content/css/bootstrap-datepicker.css">
    <link rel="stylesheet" href="~/Content/css/jquery.timepicker.css">


    <link rel="stylesheet" href="~/Content/css/flaticon.css">
    <link rel="stylesheet" href="~/Content/css/icomoon.css">
    <link rel="stylesheet" href="~/Content/css/style.css">

    <link rel="stylesheet" type="text/css" href="~/Content/PagedList.css">


</head>
<body>
  L
        <a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
     
       
     
            @Html.Partial("Aside")
        <div id="colorlib-main">
            @RenderBody()

            @Html.Partial("Footer")
        </div><!-- END COLORLIB-MAIN -->
        
       
    </div><!-- END COLORLIB-PAGE -->
    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>


    <script src="~/Content/js/jquery.min.js"></script>
    <script src="~/Content/js/jquery-migrate-3.0.1.min.js"></script>
        <script src="~/Content/js/popper.min.js"></script>
        <script src="~/Content/js/bootstrap.min.js"></script>
        <script src="~/Content/js/jquery.easing.1.3.js"></script>
        <script src="~/Content/js/jquery.waypoints.min.js"></script>
        <script src="~/Content/js/jquery.stellar.min.js"></script>
        <script src="~/Content/js/owl.carousel.min.js"></script>
        <script src="~/Content/js/aos.js"></script>
        <script src="~/Content/js/jquery.animateNumber.min.js"></script>
        <script src="~/Content/js/bootstrap-datepicker.js"></script>
        <script src="~/Content/js/jquery.timepicker.min.js"></script>
        <script src="~/Content/js/scrollax.min.js"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
        <script src="~/Content/js/google-map.js"></script>
        <script src="~/Content/js/main.js"></script>


</body>
</html>

ads/Views/Shared/Aside.cshtml
@using Microsoft.AspNet.Identity
@using System;
@using System.Collections.Generic;
@using System.Data;
@using System.Data.Entity;
@using System.Linq;
@using System.Threading.Tasks;
@using System.Net;
@using System.Web;
@using System.Web.Mvc;
@using ads.Models;

@if (Request.IsAuthenticated)
            {
                ApplicationDbContext db = new ApplicationDbContext();
                var idUser = User.Identity.GetUserId();
                var countMess = db.Chats.SelectMany(c => c.ChatUsers, (c, cu) => new { Chat = c,
                    ChatUser = cu }).SelectMany(c => c.Chat.Messages, (ccu, m) => new { Chat = ccu.Chat, ChatUser = ccu.ChatUser, Messages = m }).
            Where(c => c.ChatUser.idUser == idUser && c.Messages.idSender != idUser && c.Messages.isRead == false).Count();


                var countReviews = db.Reviews.Where(r => r.idRecipient == idUser && r.isRead == false).Count();


                if (User.IsInRole("Admin"))
                {
        <aside id="colorlib-aside" role="complementary" class="js-fullheight text-center">
            <h1 id="colorlib-logo"><a href="/"><span class="icon-bullhorn"></span>free ads</a></h1>
            <nav id="colorlib-main-menu" role="navigation">

                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
            @Html.AntiForgeryToken()

            <ul>

                <li>@Html.ActionLink("Обьявления", "AdminIndex", "Ads")</li>

                <li>@Html.ActionLink("Сообщения(" + countMess.ToString() + ")", "Index", "ChatUsers", null, null)</li>

                <li>@Html.ActionLink("Отзывы", "Index", "Reviews")</li>

                <li>@Html.ActionLink("Настройки профиля", "Index", "Manage", routeValues: null, htmlAttributes: null)</li>

                <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>

            </ul>
                }
            </nav>
        </aside> <!-- END COLORLIB-ASIDE -->
    }
    else
    {
        <aside id="colorlib-aside" role="complementary" class="js-fullheight text-center">
            <h1 id="colorlib-logo"><a href="/"><span class="icon-bullhorn"></span>free ads</a></h1>
            <nav id="colorlib-main-menu" role="navigation">

                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
        @Html.AntiForgeryToken()

        <ul>

            <li>@Html.ActionLink("Подать обьявление", "Create", "Ads")</li>

            <li><a href="/Ads">Все объявления</a></li>

            <li>@Html.ActionLink("Мои обьявления", "UserAds", "Ads", routeValues: new { id = HttpContext.Current.User.Identity.GetUserId() }, htmlAttributes: null)</li>

            <li>@Html.ActionLink("Сообщения(" + countMess.ToString() + ")", "Index", "ChatUsers", null, null)</li>

            <li>@Html.ActionLink("Отзывы(" + countReviews.ToString() + ")", "About", "Reviews", new { id = HttpContext.Current.User.Identity.GetUserId() }, null)</li>

            <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>

        </ul>
                }
            </nav>
        </aside> <!-- END COLORLIB-ASIDE -->
    }

}
else
{
    <aside id="colorlib-aside" role="complementary" class="js-fullheight text-center">
        <h1 id="colorlib-logo"><a href="index.html"><span class="icon-bullhorn"></span>free ads</a></h1>
        <nav id="colorlib-main-menu" role="navigation">
            <ul>
                <li>@Html.ActionLink("Регистрация", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                <li>@Html.ActionLink("Выполнить вход", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
            </ul>
        </nav>
    </aside> <!-- END COLORLIB-ASIDE -->
}

ads/Views/Shared/Footer.cshtml
<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container px-md-5">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Возникли вопросы?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><a href="/Messages/GetContact"><span class="icon icon-phone"></span><span class="text">Связаться с нами</span></a></li>
                            <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@freads.com</span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">

                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;
                    <script>document.write(new Date().getFullYear());</script>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

ads/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>