ads/Models/ReviewViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.Spatial;
using System.Web.Mvc;

namespace ads.Models
{
    public class ReviewsAboutViewModel
    {
       public List<Review> Reviews;
        public ApplicationUser Recipient;
    }
}

ads/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ads.Models;
using Microsoft.AspNet.Identity;

namespace ads.Controllers
{
    public class ReviewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Reviews
        public async Task<ActionResult> Index()
        {
            var reviews = db.Reviews.Include(r => r.UserRecipient).Include(r => r.UserSender);
            return View(await reviews.ToListAsync());
        }

        // GET: Reviews/About/jkjk-sdsa
        public async Task<ActionResult> About(string id)
        {
            if(id==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser rec = await db.Users.Where(u => u.Id == id).FirstAsync();
            if(rec==null)
            {
                return HttpNotFound();
            }
            var reviews = await db.Reviews.Where(r=>r.idRecipient==id).ToListAsync();
            if (User.Identity.IsAuthenticated && User.Identity.GetUserId() == id)
            {
                var notread = reviews.Where(r => r.isRead == false).ToList();
                for (int i = 0; i < notread.Count; i++)
                {
                    notread[i].isRead = true;
                    db.Entry(notread[i]).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                }
            }
            return View("Index",reviews);
        }

        // GET: Reviews/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = await db.Reviews.FindAsync(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // GET: Reviews/Create
        public ActionResult Create()
        {
            ViewBag.idRecipient = new SelectList(db.ApplicationUsers, "Id", "Email");
            ViewBag.idSender = new SelectList(db.ApplicationUsers, "Id", "Email");
            return View();
        }

        // POST: Reviews/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "text,idSender,idRecipient")] Review review)
        {
            if (ModelState.IsValid)
            {
                review.datetime = DateTime.Now;
                review.isRead = false;
                db.Reviews.Add(review);
                await db.SaveChangesAsync();
                return RedirectToAction("Index","Ads",null);
            }
            return View(review);
        }

        // GET: Reviews/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = await db.Reviews.FindAsync(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            ViewBag.idRecipient = new SelectList(db.ApplicationUsers, "Id", "Email", review.idRecipient);
            ViewBag.idSender = new SelectList(db.ApplicationUsers, "Id", "Email", review.idSender);
            return View(review);
        }

        // POST: Reviews/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "id,text,datetime,isRead,idSender,idRecipient")] Review review)
        {
            if (ModelState.IsValid)
            {
                db.Entry(review).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.idRecipient = new SelectList(db.ApplicationUsers, "Id", "Email", review.idRecipient);
            ViewBag.idSender = new SelectList(db.ApplicationUsers, "Id", "Email", review.idSender);
            return View(review);
        }
        [Authorize(Roles ="Admin")]
        // GET: Reviews/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Review review = await db.Reviews.FindAsync(id);
            if (review == null)
            {
                return HttpNotFound();
            }
            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Review review = await db.Reviews.FindAsync(id);
            db.Reviews.Remove(review);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ads/Views/Reviews/About.cshtml
@{
    ViewBag.Title = "Отзывы";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}
@using ads.Models
@using Microsoft.AspNet.Identity
@model ads.Models.ReviewsAboutViewModel

<section class="ftco-section bg-light ftco-bread">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center">
            <div class="col-md-10 ftco-animate">
                <p class="breadcrumbs"> <span>Отзывы</span></p>
                <hr />
            </div>
        </div>
    </div>
</section>

<ul class="comment-list">
    @foreach (var item in Model.Reviews)
    {
        <li class="comment">
            <div class="comment-body">
                <h3>@item.UserSender.UserName</h3>
                <div class="meta">@item.datetime</div>
                <p>@item.text</p>
            </div>
        </li>
    }
</ul>
@if (User.Identity.IsAuthenticated && User.Identity.GetUserId() != Model.Recipient.Id)
{
    @Html.Partial("~/Views/Reviews/CreatePartial.cshtml", new Review
{
    idRecipient = Model.Recipient.Id,
    idSender = User.Identity.GetUserId()
})
}

ads/Views/Reviews/AboutPartial.cshtml
@using Microsoft.AspNet.Identity
@using ads.Models
@model ads.Models.ReviewsAboutViewModel

@{
    ViewBag.Title = "Index";
}

    <ul class="comment-list">
        @foreach (var item in Model.Reviews)
        {
                <li class="comment">
                    <div class="comment-body">
                        <h3>@item.UserSender.UserName</h3>
                        <div class="meta">@item.datetime</div>
                        <p>@item.text</p>
                    </div>
                </li>
        }
    </ul>
@if (User.Identity.IsAuthenticated && User.Identity.GetUserId() != Model.Recipient.Id)
    {
@Html.Partial("~/Views/Reviews/CreatePartial.cshtml", new Review
{
    idRecipient = Model.Recipient.Id,
    idSender = User.Identity.GetUserId()
})
}

ads/Views/Reviews/Create.cshtml
@model ads.Models.Review

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Review</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.datetime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datetime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.datetime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isRead, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isRead)
                    @Html.ValidationMessageFor(model => model.isRead, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idSender, "idSender", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idSender", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idSender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idRecipient, "idRecipient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idRecipient", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idRecipient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ads/Views/Reviews/CreatePartial.cshtml
@model ads.Models.Review
@using Microsoft.AspNet.Identity

<div class="comment-form-wrap pt-5">
    <h3 class="mb-5">Написать отзыв</h3>
        @using (Html.BeginForm("Create", "Reviews", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.idSender)
            @Html.HiddenFor(model => model.idRecipient)
            <div class="col text-center">
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.text, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control",
                           @cols = "30",
                           @rows = "4"
                       }
                   })
                        @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
                    </div>
                </div>
                </div>
                <div class="sidebar-box col text-center">
                    <div class="form-group">
                        <input type="submit" value="Отправить" class="btn btn-primary py-3 px-5">
                    </div>
                    </div>
        }
                </div>

ads/Views/Reviews/Delete.cshtml
@model ads.Models.Review

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Review</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserRecipient.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserRecipient.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserSender.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserSender.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isRead)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isRead)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ads/Views/Reviews/Details.cshtml
@model ads.Models.Review

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Review</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserRecipient.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserRecipient.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserSender.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserSender.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.datetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isRead)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isRead)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ads/Views/Reviews/Edit.cshtml
@model ads.Models.Review

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Review</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.datetime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datetime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.datetime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isRead, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isRead)
                    @Html.ValidationMessageFor(model => model.isRead, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idSender, "idSender", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idSender", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idSender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idRecipient, "idRecipient", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idRecipient", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idRecipient, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ads/Views/Reviews/Index.cshtml
@model IEnumerable<ads.Models.Review>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/ADSLayout.cshtml";
}

<section class="ftco-section bg-light ftco-bread">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center">
            <div class="col-md-10 ftco-animate">
                <p class="breadcrumbs"> <span>Отзывы</span></p>
                <hr />
            </div>
        </div>
    </div>
</section>

<table class="table">
    <tr>
        <th>
            @Html.Label("Имя")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.datetime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserSender.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.datetime)
        </td>
        @if (User.IsInRole("Admin"))
        {
        <td>
            @Html.ActionLink("Удалить", "Delete", new { id = item.id })
        </td>
        }

    </tr>
}

</table>